### ISSUE TITLE
Task Priority - duplication

### ISSUE THREAD

**Issue by rbur** [fromcouch/refreak#14]
There is a duplication of "Low Priority" and "Very Low Priority" for tasks.
/application/language/english/tasks_lang.php

![rf4](https://f.cloud.github.com/assets/5042056/823993/2a0c9a18-f02e-11e2-8899-527d72fc8e2f.jpg)

**Comment by fromcouch** [comment]
Hi,

When you specify priority 9 in taskfreak, select box in new/edit task appeas with this value. This will be change when I begin with Issue #6 

Thanks

**Comment by fromcouch** [comment]
Hi, you only need to change the value of this array.
