### ISSUE TITLE
Server Side Error - Administrator edit - task project

### ISSUE THREAD

**Issue by rbur** [fromcouch/refreak#18]
When a Administrator does a task edit and clicks on the "new project" link, a new task can be created but when saved there is a "Server Side Error".

**Comment by fromcouch** [comment]
Posible as same Issue #22

**Comment by fromcouch** [comment]
You need first normalize data in tables.

**Comment by rbur** [comment]
I have been giving this problem some thought.  Perhaps it's undesirable for the user to be able to create a project while editing a task.
Projects should be created using the Manage>>Projects protocol which then allows users to be assigned to a project.
I think this capability just adds complexity.

I would recommend removing the "new project" link from the task edit.
