### ISSUE TITLE
SQL Data - tables not being cleaned up after deletes

### ISSUE THREAD

**Issue by rbur** [fromcouch/refreak#22]
After having created a couple of projects and then deleting them, I notice that the Manage >>Projects screen displays shows extra members on the existing project.

I have 3 users but the display shows 5.
![rf11](https://f.cloud.github.com/assets/5042056/829736/57f201d4-f0fb-11e2-87b2-f2e55bea3424.jpg)

The SQL table (RFK_USERS) correctly contains the right number of users 
![rf12](https://f.cloud.github.com/assets/5042056/829739/d1c88a46-f0fb-11e2-8763-4d50faaf6f91.jpg)

Table RFK_USERS_GROUPS data is ok.

The RFK_PROJECTS table contains 1 deleted project
![rf13](https://f.cloud.github.com/assets/5042056/829763/bcc763c6-f0fe-11e2-8a14-30c134c3a4bf.jpg)

The RFK_PROJECT_STATUS table contains a deleted project.
![rf14](https://f.cloud.github.com/assets/5042056/829753/9d835444-f0fd-11e2-879b-2c2e835aafed.jpg)

The RFK_USER_PROJECT contains wrong data
![rf15](https://f.cloud.github.com/assets/5042056/829761/726b756a-f0fe-11e2-9888-6326cc690a8b.jpg)

**Comment by fromcouch** [comment]
You need first normalize data in tables.
