### ISSUE TITLE
Security Error - Status Updating - devel ver Jul28/13

### ISSUE THREAD

**Issue by rbur** [fromcouch/refreak#28]
User position in project = Member
When trying to update task status get "Error by Security Reasons"

Status change is NOT saved.

**Comment by fromcouch** [comment]
Ron, 

what general level have user?

Guest, Developer, Managers,Administrator??

**Comment by rbur** [comment]
Guest

**Comment by rbur** [comment]
This has changed .....  now when the user clicks on a status completion, the task edit viewing window opens.
Unable to change status.
user level = Guest
Project position = member

**Comment by fromcouch** [comment]
Hi,

guest only can see public tasks.
This is an error.

**Comment by rbur** [comment]
Sorry ... I see no change ... not fixed
