### ISSUE TITLE
Project Delete DB Error

### ISSUE THREAD

**Issue by Ryahn** [fromcouch/refreak#29]
When trying to delete the project that comes installed, you get a deletion error from the database but the project will be deleted.

http://gyazo.com/01b315656ba33bf5c561208ff0ed2caa

**Comment by rbur** [comment]
@Ryahn .... make sure that you are using the latest code from the Development Branch.  Victor has fixed many issues and not all have been committed to the main branch yet.
I'm having no problem deleting projects right now .... although that may change... LOL
Ron....

**Comment by Ryahn** [comment]
Alright, I will see if I run into anything else
