### ISSUE TITLE
Task Creation - New Project - devel ver Jul28/13

### ISSUE THREAD

**Issue by rbur** [fromcouch/refreak#30]
The old link to create a new project from within task edit or new todo task left over from a previous fix should be removed.  All it now does is toggle to a message that says "Show list".  It serves no useful purpose.

![rf0](https://f.cloud.github.com/assets/5042056/880117/906f3ed2-f934-11e2-94fb-2bbdaf8927e5.jpg)

**Comment by fromcouch** [comment]
Hi Ron, 

When you click "new project" link, the text change to "show list", but dropdown selector is changed to input box. This allow you to create project in task popup.

Regards, 
Victor
