### ISSUE TITLE
Viewing with IE 8 on Win XP - devel ver Jul28/13

### ISSUE THREAD

**Issue by rbur** [fromcouch/refreak#32]
All the header info and menu bar is not visible in IE8.
Windows XP IE 8 is not upgradeable to a higher version of IE.

![rf3](https://f.cloud.github.com/assets/5042056/883557/c74a22a4-f98a-11e2-832b-ab7686683c49.jpg)

**Comment by fromcouch** [comment]
Hi Ron,

Menu bar is HTML 5. 

Like Footer and some other components. I will see if I can do something.

**Comment by fromcouch** [comment]
Hi Ron,

Only html5 ready browsers.
