### ISSUE TITLE
Browser Font SIze - Logo Placement  devel ver Jul28/13

### ISSUE THREAD

**Issue by rbur** [fromcouch/refreak#33]
Depending on the size of browser font (IE and Firefox) the refreak logo drops down below the menu bar.

![rf4](https://f.cloud.github.com/assets/5042056/883798/10b6d39a-f997-11e2-86a1-7dc61fbba885.jpg)

**Comment by fromcouch** [comment]
Refreak is not prepared for IE. 
Sorry
