### ISSUE TITLE
Plugin - Error Message - devel ver Jul31/13

### ISSUE THREAD

**Issue by rbur** [fromcouch/refreak#34]
When a user access the Config>>Plugin and clicks on the plugin name (it shows up as a link), they get a 404 error.
All users get this including administrator.

![rf1](https://f.cloud.github.com/assets/5042056/888523/006c18ec-fa0f-11e2-9e86-f5193d62f0f4.jpg)

![rf0](https://f.cloud.github.com/assets/5042056/888505/c1b8ccee-fa0e-11e2-8170-1d05cfff4e81.jpg)

**Comment by fromcouch** [comment]
Hi Ron, 

isn't developed yet.
