### ISSUE TITLE
Manage Users - Error Message - Admin - devel ver Jul31/13

### ISSUE THREAD

**Issue by rbur** [fromcouch/refreak#35]
When an administrator is logged in and selects Manage>>Users and selects his own name (img *1) get an error message (img *2). Selecting the edit icon allows normal edit (img *3).
Selecting the users edit icon (img *4) directly works ok ... no error. 

*1
![rf0](https://f.cloud.github.com/assets/5042056/891236/4220acd0-fa50-11e2-9686-68127e6e723a.jpg)

*2
![rf1](https://f.cloud.github.com/assets/5042056/891219/fecbdffa-fa4e-11e2-8574-1b906d3425b9.jpg)

*3
![rf4](https://f.cloud.github.com/assets/5042056/891231/a565b94e-fa4f-11e2-8c4a-26d4ae8799a7.jpg)

*4
![rf5](https://f.cloud.github.com/assets/5042056/891266/f7c1ae54-fa50-11e2-85e2-8a1c2e2b15ec.jpg)

**Comment by fromcouch** [comment]
Hi Ron, 

yes, is a old know bug. Look in text "Created on ... ". No name appears when your name or admin name have to appear in text.

I need to fix.

**Comment by rbur** [comment]
checked ok
