### ISSUE TITLE
Manage Users - Create New User - devel ver Jul31/13

### ISSUE THREAD

**Issue by rbur** [fromcouch/refreak#36]
Administrator clicks on Manage>>New Users and clicks new icon.  Gets the new user profile screen but the City field has the administrators login name filled in and the password appears to be filled in as well.

![rf0](https://f.cloud.github.com/assets/5042056/891378/20b38738-fa56-11e2-9422-86ef30d2cd2a.jpg)

**Comment by fromcouch** [comment]
Hi Ron, I can't see the problem. I reproduce your clicks but something else you do because i don't see password in create user page.

**Comment by rbur** [comment]
Ah Ha .... this is a Firefox cache issue.  This does not happen with IE or
Chrome if they are new to the program.  Is there any way to have refreak clean those fields when making a
new user ?
