### ISSUE TITLE
View Projects - Project filter - devel ver Jul31/13

### ISSUE THREAD

**Issue by rbur** [fromcouch/refreak#38]
Looks like all filtering is broken.....

The View>>Projects>> (All Tasks, Past Tasks or Future Tasks) does not filter appropriately  for the specified project.

My Tasks does not work either.

Context filtering does not work.

In all cases, all projects and tasks are displayed.

**Comment by fromcouch** [comment]
Hi,

I think that this problem was solved in another issue.
I see that is working fine.

Thanks

**Comment by rbur** [comment]
NOPE ... not quite ..... View >> Future tasks does NOT filter.  It continues to display all tasks whether in ALL projects or a selected project.

**Comment by fromcouch** [comment]
Hi Ron, 

I think I know the mistake. Future Task shows ALL not closed task. 
If you don't close task, the task appears in Future task until you close. (status 100%)
