### ISSUE TITLE
auth/login No input file specified.

### ISSUE THREAD

**Issue by uro** [fromcouch/refreak#39]
No input file specified. in auth/login after install.

**Comment by uro** [comment]
ok i solve it ! 
new .htaccess 

############################

DirectoryIndex index.php
RewriteEngine on
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond $1 !^(index.php|robots.txt)
RewriteRule ^(.*)$ index.php?/$1 [L]

**Comment by fromcouch** [comment]
Hi oparkadiusz,

I don't understand exactly your problem.
Sorry.
