### ISSUE TITLE
Users view - 404 error when click new user button

### ISSUE THREAD

**Issue by kikoot** [fromcouch/refreak#41]
I got a 404 error when i click on the create new user button in the users view table header.

In the user view file, 
line 12 causes error

``` php
site_url() . '/users/create_user/',
```

fixed

``` php
site_url() . 'users/create_user/',
```

**Comment by fromcouch** [comment]
Thanks you kikoot. Solved in development branch.
This happens when you are using PHP 5.4 or greater. :)
