### ISSUE TITLE
Config - Plugin

### ISSUE THREAD

**Issue by rbur** [fromcouch/refreak#42]
Master Branch

When selecting the Config >> Plugin get the following error

![12-23-2013 2-14-05 pm](https://f.cloud.github.com/assets/5042056/1803014/e821e9d8-6c0f-11e3-9b13-87800edc2f9e.jpg)

**Comment by fromcouch** [comment]
Hi Ron, 

Now Master and Development branch are equals.
Please, change the content of plugins/example/install.json for this:

{
    "plugin_name": "example",
    "class": "Example",
    "controller": "plugin"
}

and comment me if error disappears.

Thank you

**Comment by rbur** [comment]
Latest version downloaded from Master on Dec.29, 2013

It worked fine for the email-notifications but I got errors when I did the example.
But then the errors went away ...  and they both work ok now. 

Array ( [0] => stdClass Object ( [id] => 5 ) )
A PHP Error was encountered

Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\cchm_may9\refreak-master-dec-29-2013\application\models\plugin_handler_model.php:121)

Filename: libraries/Session.php

Line Number: 675
A PHP Error was encountered

Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\cchm_may9\refreak-master-dec-29-2013\application\models\plugin_handler_model.php:121)

Filename: helpers/url_helper.php

Line Number: 540
