### ISSUE TITLE
Task Date

### ISSUE THREAD

**Issue by rbur** [fromcouch/refreak#43]
When creating a new task - NOT entering a date into the DEADLINE field results in a date of " 1969-12-31 ".
Maybe this should be a required field so that a null cannot be entered ??

**Comment by fromcouch** [comment]
Do you are using Windows as a server for refreak?
I see the same but for me the date is 1970-01-01

**Comment by fromcouch** [comment]
I've solved. 

thank you

But, please, answer question, Do you are using Windows as a server for refreak?

**Comment by rbur** [comment]
Yes ... I use XAMPP.  I will download from the Master again and try it ... let you know later.

**Comment by rbur** [comment]
OK ... I tested again and the problem is still there.  This is with latest version downloaded from the Master.

![rf29-1](https://f.cloud.github.com/assets/5042056/1820754/fde1c73a-7104-11e3-944d-52e7e95ec61b.jpg)

![rf29-2](https://f.cloud.github.com/assets/5042056/1820756/09ad445e-7105-11e3-9dae-b203c5c997ce.jpg)

**Comment by fromcouch** [comment]
Hi Ron, now is correct. If you dosen't select date, system saves to database with this date (1969 for windows and 1970 for linux based systems) and then when is detected refreak knows that is no date and shows "-".
