### ISSUE TITLE
login

### ISSUE THREAD

**Issue by TwinMist** [fromcouch/refreak#5]
when i have run the install and it has completed, i just get a blank page  when i goto try and log in
http://xxx.xxx.xxx.xxx/refreak/auth/login
apache error log....
[Sat Jun 08 06:43:44 2013] [error] [client 86.10.41.34] PHP Warning:  require_once(/var/www/refreak/core/CodeIgniter.php): failed to open stream: No such file or directory in /var/www/refreak/index.php on line 202
[Sat Jun 08 06:43:44 2013] [error] [client 86.10.41.34] PHP Fatal error:  require_once(): Failed opening required '/var/www/refreak/core/CodeIgniter.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/refreak/index.php on line 202

**Comment by fromcouch** [comment]
Hi, 

is a tipical CodeIgniter problem.
look into application/config/config.php the $config['base_url'] value. is this correct?
Do you have correct permissions in this folder?

Thank You

**Comment by fromcouch** [comment]
Hi, ,

so sorry. There is a problem in Install instructions. I forgot add config.php. Also, I think that i need join all configuration files. 

do you resolve issue?

Thank you.
