### ISSUE TITLE
Configuration of Priority and Status Levels

### ISSUE THREAD

**Issue by rbur** [fromcouch/refreak#6]
Where are the configuration settings for the Status and Priority levels located ?

reference config code from TaskFreak:
// number of priority levels
define('FRK_PRIORITY_LEVELS',3);    // 3, 5 or 9
// how many levels to get status at 100%
define('FRK_STATUS_LEVELS',1);      // 1 to 5

**Comment by fromcouch** [comment]
Hi, 

isn't implement. I can schedule for next development.
Do you change this values in normal taskfreak operation?

Thanks

**Comment by rbur** [comment]
In my use (a small rural museum) I have only the need at present for
"High", "Medium", "Low" priority.
In our case the task status is either "Done" or "Not Done".  In TaskFreak I
have it set for one status level and wen the user clicks on the status ...
the job is done.

I will also being editing the "Contexts" drop down ....  is this possible
??  I tried in /application/language/english/tasks_lang.php but it doesn't
work
edit:  actually editing the file does affect the context when creating a new task or editing a new one BUT it does not show up on the view context dropdown box.  Must be coming from a different source ??

Ron...

**Comment by fromcouch** [comment]
Hi Ron,

You can edit Priority, if you only want 3 elements (High, Medium, Low) edit array in task_lang.php and then priority select box change in show/edit task windows.

Contexts are a little bit complicated. Yau can edit in same way that priority, but you lose colors in show and list screens (I will see to fix this and explain how to change in readme.md)

`edit:  actually editing the file does affect the context when creating a new task or editing a new one BUT it does not show up on the view context dropdown box.  Must be coming from a different source ??`

There is only one place for define context. Try CTRL+F5 or CMD+R (if you have mac) to clean cache.

Victor

**Comment by rbur** [comment]
Contexts:  - Sorry but the contexts are from two places.
1) Context list in   /application/language/english/tasks_lang.php
2) Context list in    /application/language/english/layout/header_lang.php

The two differences:

![rf5](https://f.cloud.github.com/assets/5042056/825736/416588be-f074-11e2-8ae2-f0a6a7593573.jpg)

![rf6](https://f.cloud.github.com/assets/5042056/825742/6c1c9a70-f074-11e2-93ff-cc57ad9e9f62.jpg)

**Comment by fromcouch** [comment]
Ops ... solved :)
